name: PyPI publish

on:
  workflow_call:
    inputs:
      package_version:
        description: "The version used to publish to the registry."
        type: string
        required: true
      test_pypi:
        description: "Parameter to publish the package to Test PyPI when set to 'true', and to publish to official Pypi when set to 'false'."
        type: string
        required: true
      python_latest:
        description: 'Use the latest Python version (3.12)'
        required: true
        default: false
        type: boolean

jobs:

  build-package:
    name: Build Package with Verified Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4

      - name: Validate Version Tag
        uses: ghga-de/gh-action-pypi/verify-version-tag@c350d120fad0e7e6eef85cf513a267291b3f26b4
        with:
          tag: ${{ inputs.package_version }}

      - name: Build Python Package
        uses: ghga-de/gh-action-pypi/build-python-package@c350d120fad0e7e6eef85cf513a267291b3f26b4

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./dist

  test-package:
    name: Test Freshly Built Package
    needs: build-package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4

      - name: Download dist content
        uses: actions/download-artifact@v4
      
      - name: Test with Python 3.12 using the test-package action
        if: ${{ inputs.python_latest }}
        uses: ghga-de/gh-action-pypi/test-package@c350d120fad0e7e6eef85cf513a267291b3f26b4
        with:
          python_version: 3.12

      - name: Test with Python 3.9-3.12 using the test-package action
        if: ${{ !inputs.python_latest }}
        uses: ghga-de/gh-action-pypi/test-package@c350d120fad0e7e6eef85cf513a267291b3f26b4
        with:
          python_version: ${{ matrix.python-version }}

  publish-package:
    name: Publish Package
    needs: test-package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4

      - name: Download dist content
        uses: actions/download-artifact@v4

      - name: Publish using the publish-package action
        uses: ghga-de/gh-action-pypi/publish-package@c350d120fad0e7e6eef85cf513a267291b3f26b4
        with:
          test_pypi_api_token: ${{ secrets.TEST_PYPI_API_TOKEN }}
          pypi_api_token: ${{ secrets.PYPI_API_TOKEN }}
          test_pypi: ${{ inputs.test_pypi }}